name: CICD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Installing Dependencies
        run: npm install

      - name: Make permission to executable
        run: sudo chmod +x android/gradlew

      - name: build to apk
        run: cd android && ./gradlew assembleRelease

      - name: Upload artifact for job 1
        uses: actions/upload-artifact@v2
        with:
          name: release-app
          path: android/app/build/outputs/apk/release/app-release.apk

      - name: Listing result
        run: ls android/app/build/outputs/apk

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact for job 1
        uses: actions/download-artifact@v2
        with:
          name: release-app
          path: android/app/build/outputs/apk/release/app-release.apk

      - name: Listing
        run: ls android/app/build/outputs/apk/release

      - name: Make dist folder
        run: mkdir dist

      - name: Zipping
        run: zip -r dist/app-release.zip android/app/build/outputs/apk/release/app-release.apk

      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/app-release.zip
          tag: v1
          overwrite: true
          body: "The first release app build with React, This App developed by umar"
