name: CICD

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Android App
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Building
        run: |
          sudo chmod +x android/gradlew
          cd android && ./gradlew assembleRelease

      - name: List result
        run: |
          ls android/app/build/apk
