name: CICD

on:
  push:
    branches:
      - master

jobs:
  preparation:
    name: Preparation setting
    runs-on: ubuntu-latest

    steps:
      - name: Checking dependencies
        run: |
          git --version
          node -v
          npm -v
      - name: Installing dependencies
        run: |
          npm install

  build-top-apk:
    name: Make build to android app
    runs-on: ubuntu-latest

    steps:
      - name: Listing
        run: ls android

