name: CICD

on:
  push:
    branches:
      - master

jobs:
  preparation:
    name: Preparation setting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Checking dependencies
        run: |
          git --version
          node -v
          npm -v
      - name: Installing dependencies
        run: |
          npm install

      - name: Make permission
        run: sudo chmod +x android/gradlew

      - name: Build to apk
        run: |
          cd android && ./gradlew assembleRelease

      - name: List result
        run: |
          ls android/app/build/outputs/apk

      - name: uploading artifact
        uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: android/app/build/outputs/apk/app-release.apk


