name: CICD

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Android App
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: List result
        run: |
          ls android/app/build/outputs/

# - name: uploading artifact
# uses: actions/upload-artifact@v2
# with:
# name: release-apk
# path: android/app/build/outputs/apk/app-release.apk


